$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  units:
    type: string
  univec:
    type: object
    properties:
      core:
        type: boolean
    required:
      - core

required:
  - units
  - univec
